-- -*- tab-width: 4 -*- -
--
-- packages/institution/sql/oracle/access-drop.sql
--
-- Drop Script for UCLA ACCESS specific data.
--
-- @author			helsleya@cs.ucr.edu
-- @creation-date	2005-01-10
-- @cvs-id			$Id: access-drop.sql,v 1.1.1.1 2006/09/13 01:29:58 nsadmin Exp $
--
drop table access_personnel;
